[project]
name = "fliboria"
version = "0.1.0"
requires-python = ">=3.13"
dependencies = [
    "alembic>=1.17.2",
    "fastapi[standard]>=0.121.2",
    "psycopg2>=2.9.11",
    "pydantic-settings>=2.12.0",
    "sqlmodel>=0.0.27",
]
